# Generated by Django 3.1.2 on 2020-10-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Booking',
        ),
    ]
